# AuraNet Conda Environment for CUDA 11.4
# Use this file to create a conda environment with basic dependencies
# PyTorch will be installed separately due to CUDA requirements
# 
# Usage:
#   conda env create -f environment_cuda114.yml
#   conda activate auranet-cuda114
#   pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
#   pip install -r requirements_cuda114.txt

name: auranet-cuda114

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.11
  
  # CUDA toolkit (compatible with CUDA 11.4)
  - cudatoolkit=11.8
  
  # Core scientific computing from conda-forge
  - numpy=1.24.*
  - scipy=1.10.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  
  # Computer vision
  - opencv=4.8.*
  - pillow=9.5.*
  
  # Data handling
  - pandas=2.0.*
  - h5py=3.9.*
  
  # Configuration
  - pyyaml=6.0.*
  
  # Development tools
  - jupyter
  - ipykernel
  - pytest=7.4.*
  
  # System utilities
  - psutil=5.9.*
  
  # Git (useful for development)
  - git
  
  # pip for additional packages
  - pip
