# AuraNet Conda Environment for CUDA 11.4
# Use this file to create a conda environment with all dependencies
# 
# Usage:
#   conda env create -f environment_cuda114.yml
#   conda activate auranet-cuda114

name: auranet-cuda114

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.11
  
  # CUDA toolkit (compatible with CUDA 11.4)
  - cudatoolkit=11.8
  
  # Core scientific computing from conda-forge
  - numpy=1.24.*
  - scipy=1.10.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  
  # Computer vision
  - opencv=4.8.*
  - pillow=9.5.*
  
  # Data handling
  - pandas=2.0.*
  - h5py=3.9.*
  
  # Configuration
  - pyyaml=6.0.*
  
  # Development tools
  - jupyter
  - ipykernel
  - pytest=7.4.*
  
  # System utilities
  - psutil=5.9.*
  
  # Git (useful for development)
  - git
  
  # pip for additional packages
  - pip
  
  # Install via pip (packages not available or not optimal via conda)
  - pip:
    # PyTorch stack (CUDA 11.8 compatible with CUDA 11.4)
    - torch==2.0.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
    - torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
    - torchaudio==2.0.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
    
    # Deep learning utilities
    - timm>=0.6.0,<0.10.0
    - einops>=0.6.0,<0.8.0
    - torchmetrics>=0.11.0,<1.3.0
    - pytorch-metric-learning>=1.6.0,<2.1.0
    - pytorch-lightning>=2.0.0,<2.2.0
    - accelerate>=0.20.0,<0.25.0
    
    # Signal processing
    - pywavelets>=1.4.0,<1.5.0
    
    # Computer vision
    - scikit-image>=0.19.0,<0.22.0
    - imageio>=2.22.0,<2.32.0
    - albumentations>=1.3.0,<1.4.0
    - facenet-pytorch>=2.5.0,<2.6.0
    
    # Machine learning
    - scikit-learn>=1.1.0,<1.4.0
    
    # Logging and monitoring
    - tensorboard>=2.10.0,<2.15.0
    - tensorboardX>=2.6,<2.7.0
    - wandb>=0.15.0,<0.17.0
    
    # Configuration utilities
    - omegaconf>=2.3.0,<2.4.0
    - hydra-core>=1.3.0,<1.4.0
    
    # Progress bars and CLI
    - tqdm>=4.64.0,<4.67.0
    - click>=8.1.0,<8.2.0
    - rich>=13.0.0,<14.0.0
    
    # Visualization
    - plotly>=5.15.0,<5.18.0
    
    # Metrics and losses
    - pytorch-ssim>=0.1.0
    - pytorch-msssim>=0.2.1
    - torcheval>=0.0.6,<0.0.8
    
    # Memory profiling
    - py3nvml>=0.2.7,<0.3.0
    
    # File I/O
    - zarr>=2.12.0,<2.17.0
    
    # Development tools
    - black>=23.0.0,<24.0.0
    - flake8>=6.0.0,<6.2.0
    - mypy>=1.0.0,<1.8.0
    - ipywidgets>=8.0.0,<8.2.0
    
    # Optional: Memory efficient attention (uncomment if needed)
    # - xformers==0.0.16  # CUDA 11.4 compatible version
    
    # Optional: CuPy for CUDA 11.4 (uncomment if needed for custom ops)
    # - cupy-cuda114>=11.0.0
