# AuraNet Base Configuration
# Common settings shared across all resolutions

# Dataset Configuration
dataset:
  name: "celeb_df"
  data_root: "path/to/celeb-df-dataset"  # Will be overridden by command line
  subfolders:
    real: "celeb-df-real"
    fake: "celeb-df-fake" 
    mask: "celeb-df-mask"
  
  # Train/Test split configuration
  split_ratio: 0.75  # 75% train, 25% test
  sampling_strategy: "sorted_index_based"
  split_modulo: 4
  match_fake_to_mask: true

# Classification
num_classes: 2

# Model architecture hyperparameters
model:
  # Attention parameters
  attention_dropout: 0.0
  
  # Dropout rates
  classification_dropout: 0.15
  cross_fusion_dropout: 0.0
  
  # Reduction ratios for attention mechanisms
  se_reduction: 16
  cbam_reduction: 16
  
  # Contrastive learning
  contrastive_projection_dim: 128
  contrastive_hidden_dim: 512
  
  # AM-Softmax parameters
  am_softmax_margin: 0.35
  am_softmax_scale: 30.0
  
  # Masking parameters
  patch_size: 32
  block_size: 16
  
  # Initial processing channels
  # These will be overridden by resolution-specific configs
  msaf_srm_channels: 20
  msaf_dwt_channels: 12
  msaf_fused_channels: 32  # Output channels of MSAF
  mbconv_output_channels: 64  # Output channels of MBConv downsampling
  mbconv_expand_ratio: 4
  
  # HAFT internal parameters
  haft_encoder_channels: [16, 32]
  haft_pooling_size: 4
  
  # Cross-attention offset scaling
  deformable_offset_scale: 0.1

# Data augmentation parameters
data_augmentation:
  horizontal_flip_prob: 0.5
  rotation_degrees: 10
  brightness: 0.1
  contrast: 0.1
  saturation: 0.1
  hue: 0.05
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Multi-GPU Training Configuration
distributed:
  enabled: true
  backend: "nccl"
  init_method: "env://"
  world_size: null
  rank: null
  local_rank: null

# Data loading parameters
data_loading:
  drop_last: true
  persistent_workers: true
  
# Evaluation parameters  
evaluation:
  save_predictions: true
  visualize_results: true
  metrics: ["accuracy", "precision", "recall", "f1", "auc", "ap"]
  mask_gt_dir: "celeb-df-mask"
  detailed_eval_freq: 1
  
# Checkpointing and logging
checkpoint:
  save_dir: "checkpoints/celeb_df"
  save_freq: 5
  save_best: true
  resume_from: null
  
logging:
  log_dir: "logs/celeb_df"
  log_freq: 100
  tensorboard: true
  wandb:
    enabled: false
    project: "auranet-celeb-df"
    entity: null

# Hardware configuration
device: "cuda"
compile_model: false

# Reproducibility
seed: 42
deterministic: false
